#include "Common.h"
#include "Graphics.h"
#include "Vertex.h"

GLfloat triangle1X = 0;
GLfloat triangle1Y = 0;
GLfloat triangle1Z = -5;
GLfloat triangle2X = 0;
GLfloat triangle2Y = 0;
GLfloat triangle2Z = -5;


Vertex verts[]{
//Front		
{-0.5f, 0.5f, 0.5f, 
1.0, 0.0f, 0.0f, 1.0f},//Top Left
{ -0.5f, -0.5, 0.5f, 
1.0f, 1.0f, 0.0f, 1.0f }, //Bottom Left
{0.5f, -0.5f, 0.5f,
0.0f, 1.0f, 1.0f, 1.0f }, //Bottom Right
{0.5f,0.5f,0.5f,
1.0f,0.0f,1.0f,1.0f}, //Top Right
{-0.5f,0.5f,0.5f,
1.0f,0.0f,1.0f,1.0f}, //Top Left
{0.5f,-0.5f,0.5f,
0.0f,1.0f,1.0f,1.0f}, //Bottom Right

//Back
{-0.5f,0.5f,-0.5f,
1.0f,0.0f,1.0f,1.0f},//Top Left

{-0.5f,-0.5f,-0.5f,
1.0f,1.0f,0.0f,1.0f}, //Bottom Left

{0.5f, -0.5f, -0.5f,
0.0f, 1.0f, 1.0f, 1.0f}, //Bottom Right

{0.5f, 0.5f, -0.5f,
1.0f,0.0f,1.0f,1.0f}, //Top Right

{-0.5f, 0.5f, -0.5f,
1.0f,0.0f,1.0f,1.0f}, //Top Left

{0.5f, -0.5f, -0.5f,
0.0f, 1.0f, 1.0f, 1.0f}, //Bottom Right

//Left
{-0.5f,0.5f-0.5f,
1.0f, 1.0f, 0.0f, 1.0f},
{-0.5f, -0.5f, -0.5f,
0.0f,1.0f,0.0f,1.0f},
{-0.5f,-0.5f, 0.5f},
{-0.5f,0.5f,0.5f,
0.0f,0.0f,1.0f,0.0f}

//Right

};

GLuint VBO;

void render()
{
	//Set the clear colour(background)
	glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
	//clear the colour and depth buffer
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	//Make VBO active
	glBindBuffer(GL_ARRAY_BUFFER, VBO);

	glVertexPointer(3, GL_FLOAT,sizeof(Vertex), NULL);

	glColorPointer(4, GL_FLOAT, sizeof(Vertex), (void**)(3 * sizeof(float)));

	glEnableClientState(GL_VERTEX_ARRAY);
	glEnableClientState(GL_COLOR_ARRAY);

	//switch to model view
	glMatrixMode(GL_MODELVIEW);
	//reset using the identity matrix
	glLoadIdentity();

	gluLookAt(0.0f, 0.0f, 6.0f, 0.0f, 0.0f, -1.0f, 0.0f, 1.0f, 0.0f);

	glTranslatef(0.0f, 0.0f, -6.0f);

	glDrawArrays(GL_TRIANGLES, 0, sizeof(verts) / (sizeof(Vertex)));

	//glLoadIdentity();

	//glTranslatef(2.0f, 0.0f, -6.0f);

	//glDrawArrays(GL_TRIANGLES, 0, sizeof(verts) / (3 * sizeof(float)));




	
}

void update()
{

}

void InitScene()
{
	//Create buffer
	glGenBuffers(1, &VBO);
	//Make the new VBO active
	glBindBuffer(GL_ARRAY_BUFFER, VBO);
	//Copy text data to VBO
	glBufferData(GL_ARRAY_BUFFER, sizeof(verts), verts, GL_STATIC_DRAW);
}

void CleanUp()
{
	glDeleteBuffers(1, &VBO);
}

int main(int argc, char * arg[])
{
	bool run = true;
	if (SDL_Init(SDL_INIT_EVERYTHING) != 0)
	{
		std::cout << "ERROR SDL_Init" << SDL_GetError() << std::endl;
		return -1;
	}
	SDL_Window * window = SDL_CreateWindow("SDL",  //Window title
							SDL_WINDOWPOS_CENTERED, // x position, centered
							SDL_WINDOWPOS_CENTERED, //y position, centered
							640,					//width in pixels
							480,					//height in pixels
							SDL_WINDOW_OPENGL		//flags
							);

	//Create an OpenGL context associated with the window
	SDL_GLContext glcontext = SDL_GL_CreateContext(window);
	
	initOpenGL();
	InitScene();

	//SetViewPort
	setViewPort(640, 480);

	//Value to hold the event generated by SDL
	SDL_Event event;
	//Game Loop
	while(run)
	{
		//While we still have events in the queue
		while (SDL_PollEvent(&event))
		{
			//Get event type
			if (event.type == SDL_QUIT || event.type == SDL_WINDOWEVENT_CLOSE)
			{
				run = false;
			}
			switch (event.type)
			{
			case SDL_KEYDOWN:
				switch (event.key.keysym.sym)
				{
				case SDLK_LEFT:
					triangle1X -= 1;
					break;
				case SDLK_RIGHT:
					triangle1X += 1;
					break;
				case SDLK_UP:
					triangle1Y += 1;
					break;
				case SDLK_DOWN:
					triangle1Y -= 1;
					break;
				}
				break;
			}
		}

		update();
		render();

		//Call swap so that our GL back buffer is displayed
		SDL_GL_SwapWindow(window); //what does this do?
	}
	CleanUp();
	SDL_GL_DeleteContext(glcontext);
	SDL_DestroyWindow(window);
	SDL_Quit(); //shouldnt this clear window as well?
    return 0;
}
